### ISSUE TITLE
The quality of synthesized audios

### ISSUE THREAD

**Issue by JohnHerry** [KunZhou9646/Emovox#2]
Hi, Mr Zhou,
     I have read the paper, the idea of emotion density control  is very attractive. 
I am not Enligsh native, but I feel the samples of proposed in https://kunzhou9646.github.io/Emovox_demo/  are not so good, they are even less intelligable or natural compared with conterpart samples.
     Is the hurt on speech quality a necessary cost when learning to be more emotional?

**Comment by KunZhou9646** [comment]
Thanks for your interests in our paper! I think there might be a few factors that can affect the synthesized quality:
1/ The perceptual losses from pre-trained SER could improve the emotional intelligibility while harming the speech quality;
2/ Since we use a small amount of data to do emotion training, the speech quality may not be very satisfactory. If more speech data and more emotion types are included, the quality would be much better.

**Comment by JohnHerry** [comment]
> Thanks for your interests in our paper! I think there might be a few factors that can affect the synthesized quality: 1/ The perceptual losses from pre-trained SER could improve the emotional intelligibility while harming the speech quality; 2/ Since we use a small amount of data to do emotion training, the speech quality may not be very satisfactory. If more speech data and more emotion types are included, the quality would be much better.

Thank you for replay.  the lack of data is a big problem. I can not found enough emotional tts speeches eighter.

**Comment by TengNN** [comment]
> > Thanks for your interests in our paper! I think there might be a few factors that can affect the synthesized quality: 1/ The perceptual losses from pre-trained SER could improve the emotional intelligibility while harming the speech quality; 2/ Since we use a small amount of data to do emotion training, the speech quality may not be very satisfactory. If more speech data and more emotion types are included, the quality would be much better.
> 
> Thank you for replay. the lack of data is a big problem. I can not found enough emotional tts speeches eighter.

Hello, the author deleted the checkpoint of stage one. Do you still have the checkpoint of stage one saved?
