### ISSUE TITLE
How can I assign opensmile_path?

### ISSUE THREAD

**Issue by hayeong0** [KunZhou9646/Emovox#4]
Hello, Thank you for sharing your work!

I have a question in the "step1. Learning relative attributes" part, `pre-processing.py`.
In the process of extracting the acoustic features with openSMILE feature, which file is used in the following path?
```python
opensmile_path = '/Users/kun/Desktop/workspace/open_smile/opensmile/build/progsrc/smilextract/SMILExtract'
config_path = '/Users/kun/Desktop/workspace/open_smile/opensmile/config/is09-13/IS09_emotion.conf'
```
I couldn't find a specific way to specify the path in the paper.

**Comment by KunZhou9646** [comment]
Hi, thanks for your questions. You need to first install OpenSmile on your own computer. You can check here https://github.com/audeering/opensmile

**Comment by hayeong0** [comment]
Thanks for your kind reply :)
I got a hint from openSMILE open source and completed that part.
When training the relative ranking function, I use the Matlab code you provided. 
Is there any Python code other than Matlab code?

**Comment by KunZhou9646** [comment]
Yeah there might be some codes using Python. But for this repo, I was using Matlab code to train the relative ranking functions and get the score first. Then I incoporate the scores into the emotion training, which is based on Python.

**Comment by hayeong0** [comment]
Okay I see, thanks :)

**Comment by cantabile-kwok** [comment]
Sorry to re-open this, but where is that `/Users/kun/Desktop/workspace/open_smile/opensmile/config/is09-13/IS09_emotion.conf'`?

**Comment by TengNN** [comment]
> Thanks for your kind reply :) I got a hint from openSMILE open source and completed that part. When training the relative ranking function, I use the Matlab code you provided. Is there any Python code other than Matlab code?

Hello, the author deleted the checkpoint of stage one. Do you still have the checkpoint of stage one saved?
