### ISSUE TITLE
Where is the `IS09_emotion.conf` file?

### ISSUE THREAD

**Issue by cantabile-kwok** [KunZhou9646/Emovox#5]
Hi thanks for the code! I was struggling with the relative attributes training part. As is mentioned in https://github.com/KunZhou9646/Emovox/issues/4#issue-1305759816, the path is set in the code and it seems nowhere I can find it in this repo.

I'm stuck at here mainly because I want to train your model on a different speaker. I would be better if you can share the csv files `strengths.txt` related to the Mixed Emotion repo on another speaker (especially 0015). Thank you!

**Comment by cantabile-kwok** [comment]
Alright, I found it is in openSMILE's repo, https://github.com/audeering/opensmile/blob/1640a786e2968e8eb1272bba82049b01dcceedfb/config/is09-13/IS09_emotion.conf

**Comment by TengNN** [comment]
> Alright, I found it is in openSMILE's repo, https://github.com/audeering/opensmile/blob/1640a786e2968e8eb1272bba82049b01dcceedfb/config/is09-13/IS09_emotion.conf

Hello, the author deleted the checkpoint of stage one. Do you still have the checkpoint of stage one saved?
